[package]
name = "nix-deployments-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.8.4", features = ["macros"] }
git2 = "0.20.2"
serde = "1.0.228"
serde_json = "1.0.143"
